---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "William G. Hardy"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
from palmerpenguins import load_penguins
df = load_penguins()
```

## QUESTION|TASK 1

__Include the tables created from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) used to create the above chart (Hint: copy the code from 2.2.1. The penguins data frame and paste each in the cells below)__


```{python}
# Include and execute your code here
df.head()
```

_include figures in chunks and discuss your findings in the figure._

```{python}
# Include and execute your code here
print("""The Palmer Penguins dataset contains information about three penguin species (Adelie, Chinstrap, and Gentoo). 
It includes measurements like flipper length, bill depth, and body mass. 
There are some missing values (NaNs) present in the dataset.""")

```


## QUESTION|TASK 2

__Recreate the example charts from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) of the textbook. (Hint: copy the chart code from 2.2.3. Creating a Plot, one for each cell below)__


```{python}
# Include and execute your code here
(ggplot(df, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point()
)
```

This chart compares the weight to flipper length of each species of penguin.
_include figures in chunks and discuss your findings in the figure._

```{python}
# Include and execute your code here
(ggplot(df, aes(x="flipper_length_mm", y="body_mass_g", color="species"))
    + geom_point()
)
```

this chart why similar to the first chart adds a line to show the average rate within each species of Penguin.

```{python}
# Include and execute your code here
(ggplot(df, aes(x="flipper_length_mm", y="body_mass_g", color="species"))
    + geom_point()
    + geom_smooth(method="lm")
)
```

This chart shows the overall average weight to flipper size combining the three species of penuin.

```{python}
# Include and execute your code here
(ggplot(df, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species"))
    + geom_smooth(method="lm")
)
```

this chart adds shape to the three species of penguin so that you can dicern between the species.

```{python}
# Include and execute your code here
(ggplot(df, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species"
    )
)
```

this Chart changes the the labels of the chart, allowing for a more clearer understand of the chart that your looking at.