---
title: "Client Report - BYU-Idaho Players and Comparing Teams"
subtitle: "Unit 2 Task 2"
author: "William Hardy"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query to create a new dataframe about baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, and the yearID/teamID associated with each salary. Order the table by salary (highest to lowest) and print out the table in your report.__

_The table shows the price range over the years increase the the longer the players play on a team, along with it changing when they get traded to a different team._

```{python}
query1 = """
SELECT cp.playerID, cp.schoolID, sal.salary, sal.yearID, sal.teamID
FROM CollegePlaying cp
JOIN Salaries sal ON cp.playerID = sal.playerID
WHERE cp.schoolID = 'idbyuid'
ORDER BY sal.salary DESC;
"""
byu_idaho_players = pd.read_sql_query(query1, con)
byu_idaho_players

```

## QUESTION 2

__Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Be creative! Write an SQL query to get the data you need, then make a graph using Lets-Plot to visualize the comparison. What do you learn?__ 

_Comparing BYU-I Kansas State University on there appearances in The MLB, is a whooping 6,324 players from Kansas State VS. BYU-I's 1,198 players._

```{python}
query2 = """
SELECT cp.schoolID, SUM(app.G_all) AS total_appearances
FROM CollegePlaying cp
JOIN Appearances app ON cp.playerID = app.playerID
WHERE cp.schoolID IN ('idbyuid', 'kansasst')
GROUP BY cp.schoolID;
"""
school_appearances = pd.read_sql_query(query2, con)
school_appearances
from lets_plot import *

from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)  # Make sure this is called once at the top!

ggplot(school_appearances, aes(x='schoolID', y='total_appearances', fill='schoolID')) + \
    geom_bar(stat='identity') + \
    ggtitle("Total MLB Appearances by School (BYU-Idaho vs Kansas State)") + \
    xlab("School ID") + ylab("Total Appearances") + \
    theme_classic()
```